CREATE DATABASE EMPLOYEETRACKER;

USE EMPLOYEETRACKER;
CREATE TABLE DEPARTMENT(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(30));


CREATE TABLE ROLE(
ID INT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(30) NOT NULL,
SALARY DECIMAL,
DEPARTMENT_ID INT,
CONSTRAINT FK1R FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(ID));

CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(30) NOT NULL,
LAST_NAME VARCHAR(30) NOT NULL,
ROLE_ID INT,
MANAGER_ID INT,
CONSTRAINT FK2D FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID));



